### ISSUE TITLE
Version 1.18

### ISSUE THREAD

**Issue by ErythroCraft** [Redempt/BetaBarrels#1]
Hi. I'm Gynzel from Spigot.

Your plugin works fine with running CraftBukkit version dev-Spigot-a5dea1c-bc14cb6 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT)

Next I post any issues you can do or not.

**Comment by boxbeam** [comment]
I'm confused, why did you open an issue to report nothing is wrong?

**Comment by ErythroCraft** [comment]
It is an issue with future request. That mean, you can create a support for 1.18

**Comment by boxbeam** [comment]
I was planning on testing the plugin, and my other plugins, for 1.18 compatibility and updating the spigot resources. The update came out yesterday, and I will still test this plugin

**Comment by ErythroCraft** [comment]
Perfect
