### ISSUE TITLE
shift + right click

### ISSUE THREAD

**Issue by ErythroCraft** [Redempt/BetaBarrels#2]
Your plugin works fine.

Is it possible for you to do a counterpart to shift + left click?

When I right click with the mouse, all items are placed in the barrel.
But it would be better if you only put one item into it when you right-click
and with shift + right click all items are thrown into the barrel.

So, I mean.

- left click = an item out
- holding shift + left click = out a stack
- right click = insert an item
- holding shift + right click = put in a stack

**Comment by boxbeam** [comment]
The behavior is like that because players will rarely want to insert just one item. If they do want to, they can take one item out of a stack and right click with it. I don't think players usually want to just add one item, though, so right clicking inserts the stack in your hand.

**Comment by ErythroCraft** [comment]
I think so. For example, if I need 10x redstone and accidentally pull 11 out of the barrel, I first have to put all 11 in the barrel and then take 10 out again. Or I carry 1 item around with me the whole time.

**Comment by boxbeam** [comment]
Or you take 1 item off the stack in your inventory and put it back in

**Comment by ErythroCraft** [comment]
Ok, wait a while. You'll see.
