### ISSUE TITLE
[Future]: Need hopper update.

### ISSUE THREAD

**Issue by ErythroCraft** [Redempt/BetaBarrels#4]
Hi.

It is not allowed to place hopper sideways on barrels.

Can you give an updete to anable this?
It can help to input items by linked chests with the Chest++ plugin.

**Comment by ErythroCraft** [comment]
The second is, hopper can not fill barrels.
![hopper](https://user-images.githubusercontent.com/76217862/165982835-2bbf3c80-4033-4686-a7c3-9c2c0cb0e918.PNG)
![2022-04-29_18 11 06](https://user-images.githubusercontent.com/76217862/165982875-53679730-36c4-4ebc-b83d-c642f22f58f9.png)

**Comment by boxbeam** [comment]
Place the hopper before the barrel. Hoppers can insert items into barrels and remove items from them. If you have further issues, please join my support discord: https://discord.gg/agu5xGy2YZ
